import scrapingCssAndJs

urls=[
 'https://www.oshiire.co.jp/wp-content/plugins/contact-form-7/includes/css/styles.css',
 'https://www.oshiire.co.jp/shared/css/import.css',
 'https://www.oshiire.co.jp/shared/js/lib/fancybox/jquery.fancybox.css',
 'https://www.oshiire.co.jp/shared/js/lib/mediabox/mediabox.css',
 'https://www.oshiire.co.jp/assets/css/import.css',
 'https://www.oshiire.co.jp/contact/css/contact_form.css',
 'https://www.oshiire.co.jp/assets/css/validationEngine.jquery.css',
 'https://www.oshiire.co.jp/scene/shared/css/detail.css',
 'https://www.oshiire.co.jp/assets/css/custom204.css',
 'https://www.oshiire.co.jp/fc/pio/css/reset.css',
 'https://www.oshiire.co.jp/fc/pio/css/common.css',
 'https://www.oshiire.co.jp/fc/pio/css/index.css',
 'https://www.oshiire.co.jp/fc/pio/css/contents.css',
 'https://www.oshiire.co.jp/shared/js/lib/facebox/facebox.css',
 'https://www.oshiire.co.jp/store/css/detail.css',
 'https://www.oshiire.co.jp/scene/shared/css/index.css',
 'https://www.oshiire.co.jp/assets/css/simulation.css',
 'https://www.oshiire.co.jp/scene/simulator/css/index.css',
 'https://www.oshiire.co.jp/begin/css/compare.css',
 'https://www.oshiire.co.jp/scene/css/index.css',
 'https://www.oshiire.co.jp/fc/pio/css/animate.css',
 'https://www.oshiire.co.jp/fc/pio/css/movie.css',
 'https://www.oshiire.co.jp/fc/pio/css/flexslider.css',
 'https://www.oshiire.co.jp/begin/css/index.css',
 'https://www.oshiire.co.jp/company_info/css/index.css',
 'https://www.oshiire.co.jp/assets/css/en-page.css',
 'https://www.oshiire.co.jp/contact/css/index.css',
 'https://www.oshiire.co.jp/assets/css/dcalendar.picker.css',
 'https://www.oshiire.co.jp/fc/css/interview.css',
 'https://container.oshiire.co.jp/lp/./css/main.css',
 'https://container.oshiire.co.jp/lp/./css/vendor/slick.css',
 'https://container.oshiire.co.jp/lp/./css/vendor/slick-theme.css',
 'https://www.oshiire.co.jp/fc/pio/css/lp.css',
 'https://www.oshiire.co.jp/fc/pio/css/responsive.css',
 'https://www.oshiire.co.jp/service/unsou/css/base.css',
 'https://www.oshiire.co.jp/fc/css/about.css',
 'https://www.oshiire.co.jp/company_info/css/history.css',
 'https://www.oshiire.co.jp/fc/css/business.css',
 'https://www.oshiire.co.jp/store/css/index.css',
]

# import元で関数を呼び出す記述があれば、先行してそちらが動いてしまう
scrapingCssAndJs.createDirectoryAndPutFiles(urls)